<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <ProjectReference Include="..\..\src\Conductor\Conductor.csproj" />
    <ProjectReference Include="..\..\src\Conductor.DependencyInjection\Conductor.DependencyInjection.csproj" />
  </ItemGroup>
</Project>
